name: learn-github-actions
on: [push]
env:
  WORKFLOW_ENV: workflow-env
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      
#   example-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Connect to PostgresSQL
#         run: node client.js
#         env:
#           POSTGRES_HOST: postgres
#           POSTGRES_PORT: 5432

  env-job:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: job-env
    steps:
      - name: Print envs
        run: echo $WORKFLOW_ENV, $JOB_ENV, $STEP_ENV
        env:
          STEP_ENV: step-env
          
  using-script-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: ./.github/scripts/build.sh
        shell: bash
  
  sharing-job-save:
    runs-on: ubuntu-latest
    name: Save output
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
  
  sharing-job-load:
    needs: sharing-job-save
    runs-on: ubuntu-latest
    name: Download output
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file
      
  expression:
    runs-on: ubuntu-latest
    env:
      myNull: ${{ null }}
      myBoolean: ${{ false }}
      myIntegerNumber: ${{711}}
      myFloatNumber: ${{ -9.2 }}
      myHexNumber: ${{ 0xff }}
      myExponentialNumber: ${{ -2.99e-2 }}
      myString: Mona the Octocat
      myStringInBraces: ${{ 'It''s open source!' }}
      shouldRun1: true
      shouldRun2: false
    steps:
      - name: Print env
        run: echo ${{ env.myNull }}, ${{ env.myBoolean }}, ${{ env.myIntegerNumber }}, ${{env.myFloatNumber}}, $myHexNumber
      - name: Should I Run1?
        if: ${{shouldRun1}}
        run: echo I'm running!
      - name: Should I Run2?
        if: ${{shouldRun2}}
        run: echo I'm running!
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
