name: learn-github-actions
on: [push]
env:
  WORKFLOW_ENV: workflow-env
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      
#   example-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Connect to PostgresSQL
#         run: node client.js
#         env:
#           POSTGRES_HOST: postgres
#           POSTGRES_PORT: 5432

  env-job:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: job-env
    steps:
      - name: Print envs
        run: echo $WORKFLOW_ENV, $JOB_ENV, $STEP_ENV
        env:
          STEP_ENV: step-env
          
  using-script-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: ./.github/scripts/build.sh
        shell: bash
  
  sharing-job-save:
    runs-on: ubuntu-latest
    name: Save output
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
  
  sharing-job-load:
    runs-on: ubuntu-latest
    name: Download output
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
